name: Windows

on: [push]

jobs:
    build:
        name: MSVC
        runs-on: 'windows-latest'
        steps:
        - uses: actions/checkout@v6
        - uses: ilammy/msvc-dev-cmd@v1
        - name: compile
          run: |
            cl /std:c++17 /EHsc /DEBUG /Fe:crashtest t.cpp Stackwalker.cpp Advapi32.lib
        - name: run
          run: |
            crashtest.exe
          shell : cmd

